//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlexanderOnTest.NetCoreWebDriverFactory.UnitTests.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class UseRealWithCustomSizeConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static UseRealWithCustomSizeConfig defaultInstance = ((UseRealWithCustomSizeConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UseRealWithCustomSizeConfig())));
        
        public static UseRealWithCustomSizeConfig Default {
            get {
                return defaultInstance;
            }
        }
    }
}
